# This workflow will install Divio CLI and deploy into Divio on a push event
 
name: Divio Continuous Deployment
 
# push event to master branch triggers the workflow
on:
 push:
   branches: [ master ]
 
# jobs run sequentially or in parallel to execute the workflow
jobs:
 
 # This workflow contains a single job called "deploy"
 deploy:
  # Setting environment variables of the secret keys for easy access
   env:
     DIVIO_API_TOKEN: ${{ secrets.DIVIO_API_TOKEN }}
     DIVIO_PROJECT_ID: ${{ secrets.DIVIO_PROJECT_ID }}  
     # DIVIO_PROJECT_SLUG: ${{ secrets.DIVIO_PROJECT_SLUG }}
  # The type of runner that this job will run on
   runs-on: ubuntu-latest
 # Steps represent a sequence of tasks that will be executed as part of the job
   steps:
   # Checks-out the repository under $GITHUB_WORKSPACE, so this job can access it
   - uses: actions/checkout@v2
   # setting up Python 3.8 to be able to run pip to install Divio CLI
   - name: Set up Python 3.8
     uses: actions/setup-python@v1
     with:
       python-version: 3.8
 
   # - name: Deploy to Divio Cloud using the API
   #   run: |
   #     curl -X POST --data 'stage="$DIVIO_PROJECT_SLUG"' --header "Authorization: Basic "$DIVIO_API_TOKEN"" https://control.divio.com/api/v1/website/"$DIVIO_PROJECT_ID"/deploy/
  
   - name: Install Divio CLI
     run: |
       python -m pip install --upgrade pip
       pip install divio-cli
  
   # Login to Divio using the access token and deploy
   - name: Deploy to Divio
     run: |
       divio login "$DIVIO_API_TOKEN"
       divio project deploy --remote-id "$DIVIO_PROJECT_ID"
